server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9999
  registerDefaultExceptionMappers: false

database:
  driverClass: "org.h2.Driver"
  url: "jdbc:h2:./database/dw-quickstart-db"

sessionCookieName: CUSTOM_SESSION